### ISSUE TITLE
Insert housekeeping data into the housekeeping table

### ISSUE THREAD

**Issue by ryankortbeek** [AlbertaSat/ex2_ground_station_website#63]
### Brief Feature Description
This task revolves around housekeeping data:

- [ ] Ensure that the schema of the [housekeeping model](https://github.com/AlbertaSat/ex2_ground_station_website/blob/107e54a4b3bb28f3a4d30615979291db146d64ca/groundstation/backend_api/models.py#L74) follows the structure of the return dictionary for the [get_hk](https://github.com/AlbertaSat/ex2_ground_station_software/blob/8d4942e049874377d1958d7d98255f1a70ae2ded/CommandDocs.txt#L99) command in ex2_ground_station_software/CommandDocs.txt
- [ ] In [comm.py](https://github.com/AlbertaSat/ex2_ground_station_website/blob/master/comm.py) post responses to get_hk commands to the housekeeping table in the database and log the response in the communications table (but don't include the content of the response as this is saved in the housekeeping table, just acknowledge successful receipt of the data)

### Priority
High

**Comment by jmmabanta** [comment]
Updates to this task:

- [ ] Modify the schema of the [housekeeping model](https://github.com/AlbertaSat/ex2_ground_station_website/blob/master/groundstation/backend_api/models.py) to match the return dictionary of the `HOUSEKEEPING.GET_HK` command (see the [here in system.py](https://github.com/AlbertaSat/ex2_ground_station_software/blob/d906c08445d93ab330546496e3e44e203cd85ed0/src/groundStation/system.py#L1040))
    - The return format of the command is rather large and is split into the housekeeping data of each subsystem (ADCS, Athena, EPS, etc.). For organization purposes, each subsystem should be its own database table that is linked to the housekeeping table (see how it's currently done with the [PowerChannels table](https://github.com/AlbertaSat/ex2_ground_station_website/blob/905bd98529d84089fda60758e3c67e3e8b71d065/groundstation/backend_api/models.py#L112) except this time it would be a [One-to-One relationship](https://docs.sqlalchemy.org/en/14/orm/basic_relationships.html#one-to-one)). 
    - Take a look at the [housekeeping documentation here ](https://github.com/AlbertaSat/ex2_ground_station_software/wiki/Housekeeping) for more information on how the command works.
    - [ ] Modification of the schema would also require modification of its [post method](https://github.com/AlbertaSat/ex2_ground_station_website/blob/905bd98529d84089fda60758e3c67e3e8b71d065/groundstation/backend_api/housekeeping.py#L54), its [validator](https://github.com/AlbertaSat/ex2_ground_station_website/blob/905bd98529d84089fda60758e3c67e3e8b71d065/groundstation/backend_api/validators.py#L113) and [fakeHousekeepingAsDict()](https://github.com/AlbertaSat/ex2_ground_station_website/blob/905bd98529d84089fda60758e3c67e3e8b71d065/groundstation/tests/utils.py#L3).
    - [ ] The [housekeeping unit tests](https://github.com/AlbertaSat/ex2_ground_station_website/blob/905bd98529d84089fda60758e3c67e3e8b71d065/groundstation/tests/test_api.py#L26) will also need to be modified.
- [ ] Update the housekeeping log visualization on the website to match the new schema
- [ ] Every passover, run the command `ex2.housekeeping.get_hk(1 0 0)` to fetch the latest hk data. `automate_communications()` [in automation.py](https://github.com/AlbertaSat/ex2_ground_station_website/blob/905bd98529d84089fda60758e3c67e3e8b71d065/automation.py#L18) should be modified so that the command above is posted to the communications list every passover.
    - [ ] In comm.py, any call to `HOUSEKEEPING.GET_HK` (check for substring in communications entry) should have the response be an acknowledgment that it was sent rather than the actual housekeeping data. The actual housekeeping data should instead be logged to the housekeeping table.

This is a fairly large task so it would be fine if we have multiple people working on the different stages of this task
